services:
  redis:
    image: "redis:alpine"
    container_name: was_redis
    restart: always
    ports: 
      - 6379:6379
    networks:
      - backnet

  mysql:
    image: "mysql:latest"
    container_name: was_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: was
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - C:/data/mysql/:/var/lib/mysql
    networks:
      - backnet

  queue:
    image: rabbitmq:3.11.26-management
    container_name: was_queue
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - C:/data/rabbitmq/:/var/lib/rabbitmq
    networks:
      - backnet
    
      
networks:
  backnet:
    name: backnet
    driver: bridge