services:
  was:
    container_name: was
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    volumes:
      - ./static:/server/static

  redis:
    image: "redis:alpine"
    container_name: was_redis
    restart: always
    ports: 
      - 6379:6379

  mysql:
    image: "mysql:latest"
    container_name: was_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: was
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - C:/data/mysql/:/var/lib/mysql
  
  
